  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: user3-quota
    namespace: user3
  spec:
    hard:
      requests.cpu: "1"
      requests.memory: 512Mi
      limits.cpu: "2"
      limits.memory: 1Gi
      pods: "10"

